name: Check code

on:
  pull_request:

concurrency:
  group: ci-check-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  format:
    name: Code format check
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Check code format with eslint and prettier
        run: yarn lint:ci

  types:
    name: TypeScript type check
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Check TypeScript type
        run: yarn tsc

  build:
    name: Build test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build test
        run: yarn build
