name: Clean up branch

on:
  pull_request:
    types:
      - closed

concurrency:
  group: ci-clean-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  clean:
    name: Delete branch
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Fetch all branches
        run: git fetch --all

      - name: Delete branch
        run: |
          git push origin --d v${{ github.event.number }}
